package li.zoss.bfh.bsc.nearby_sender;

enum NotType {
    PUBLISH_NEXT_STOP,
    PUBLISH_DELAY,
    PUBLISH_COACH_INFO,
    REQUEST_STOP,
    REQUEST_TRAIN_INFO,
    RESPONSE_TRAIN_INFO,
    REQUEST_WITH_SOUND,
    RESPONSE_WITH_SOUND
}
